[tool.poetry]
name = "hyper-db"
version = "0.1.0"
description = "A Lightweight Hypergraph Database"
authors = ["evanfeng97@gmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
